=== Naveenmadiwalar/PlacementReportsWeb/XML/addstd.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT students (student*)>
<!ELEMENT student (usn,name,branch,sem,comp,pack)>
<!ELEMENT  usn (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT branch (#PCDATA)>
<!ELEMENT sem (#PCDATA)>
<!ELEMENT comp (#PCDATA)>
<!ELEMENT pack (#PCDATA)>
<!ATTLIST usn usn CDATA #REQUIRED>

=== Naveenmadiwalar/PlacementReportsWeb/XML/addstd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students SYSTEM "addstd.dtd">
<students>
    <student>
        <usn usn="1">1</usn>
        <name>xyz</name>
        <branch>cs</branch>
        <sem>7</sem>
        <comp>xyz</comp>
        <pack>10</pack>
    </student>
</students>
